services:
  abl-builder:
    build:
      context: .
      dockerfile: Dockerfile
    image: gbl_builder:latest
    volumes:
      - .:/workspace
    command: >
      bash -c "make clean && make build && make build_module"